-- Seed file generated from free-exercise-db
-- Generated at: 2026-01-07T23:02:13.574Z

-- Use a temporary table to insert and avoid conflicts with partial index
CREATE TEMP TABLE temp_exercises (
    name text,
    target_muscle_group text,
    is_system boolean
);

INSERT INTO temp_exercises (name, target_muscle_group, is_system) VALUES
('3/4 Sit-Up', 'core', true),
('90/90 Hamstring', 'hamstrings', true),
('Ab Crunch Machine', 'core', true),
('Ab Roller', 'core', true),
('Adductor', 'glutes', true),
('Adductor/Groin', 'glutes', true),
('Advanced Kettlebell Windmill', 'core', true),
('Air Bike', 'core', true),
('All Fours Quad Stretch', 'quadriceps', true),
('Alternate Hammer Curl', 'biceps', true),
('Alternate Heel Touchers', 'core', true),
('Alternate Incline Dumbbell Curl', 'biceps', true),
('Alternate Leg Diagonal Bound', 'quadriceps', true),
('Alternating Cable Shoulder Press', 'shoulders', true),
('Alternating Deltoid Raise', 'shoulders', true),
('Alternating Floor Press', 'chest', true),
('Alternating Hang Clean', 'hamstrings', true),
('Alternating Kettlebell Press', 'shoulders', true),
('Alternating Kettlebell Row', 'back', true),
('Alternating Renegade Row', 'back', true),
('Ankle Circles', 'calves', true),
('Ankle On The Knee', 'glutes', true),
('Anterior Tibialis-SMR', 'calves', true),
('Anti-Gravity Press', 'shoulders', true),
('Arm Circles', 'shoulders', true),
('Arnold Dumbbell Press', 'shoulders', true),
('Around The Worlds', 'chest', true),
('Atlas Stone Trainer', 'back', true),
('Atlas Stones', 'back', true),
('Axle Deadlift', 'back', true),
('Back Flyes - With Bands', 'shoulders', true),
('Backward Drag', 'quadriceps', true),
('Backward Medicine Ball Throw', 'shoulders', true),
('Balance Board', 'calves', true),
('Ball Leg Curl', 'hamstrings', true),
('Band Assisted Pull-Up', 'back', true),
('Band Good Morning', 'hamstrings', true),
('Band Good Morning (Pull Through)', 'hamstrings', true),
('Band Hip Adductions', 'glutes', true),
('Band Pull Apart', 'shoulders', true),
('Band Skull Crusher', 'triceps', true),
('Barbell Ab Rollout', 'core', true),
('Barbell Ab Rollout - On Knees', 'core', true),
('Barbell Bench Press - Medium Grip', 'chest', true),
('Barbell Curl', 'biceps', true),
('Barbell Curls Lying Against An Incline', 'biceps', true),
('Barbell Deadlift', 'back', true),
('Barbell Full Squat', 'quadriceps', true),
('Barbell Glute Bridge', 'glutes', true),
('Barbell Guillotine Bench Press', 'chest', true),
('Barbell Hack Squat', 'quadriceps', true),
('Barbell Hip Thrust', 'glutes', true),
('Barbell Incline Bench Press - Medium Grip', 'chest', true),
('Barbell Incline Shoulder Raise', 'shoulders', true),
('Barbell Lunge', 'quadriceps', true),
('Barbell Rear Delt Row', 'shoulders', true),
('Barbell Rollout from Bench', 'core', true),
('Barbell Seated Calf Raise', 'calves', true),
('Barbell Shoulder Press', 'shoulders', true),
('Barbell Shrug', 'back', true),
('Barbell Shrug Behind The Back', 'back', true),
('Barbell Side Bend', 'core', true),
('Barbell Side Split Squat', 'quadriceps', true),
('Barbell Squat', 'quadriceps', true),
('Barbell Squat To A Bench', 'quadriceps', true),
('Barbell Step Ups', 'quadriceps', true),
('Barbell Walking Lunge', 'quadriceps', true),
('Battling Ropes', 'shoulders', true),
('Bear Crawl Sled Drags', 'quadriceps', true),
('Behind Head Chest Stretch', 'chest', true),
('Bench Dips', 'triceps', true),
('Bench Jump', 'quadriceps', true),
('Bench Press - Powerlifting', 'triceps', true),
('Bench Press - With Bands', 'chest', true),
('Bench Press with Chains', 'triceps', true),
('Bench Sprint', 'quadriceps', true),
('Bent-Arm Barbell Pullover', 'back', true),
('Bent-Arm Dumbbell Pullover', 'chest', true),
('Bent-Knee Hip Raise', 'core', true),
('Bent Over Barbell Row', 'back', true),
('Bent Over Dumbbell Rear Delt Raise With Head On Bench', 'shoulders', true),
('Bent Over Low-Pulley Side Lateral', 'shoulders', true),
('Bent Over One-Arm Long Bar Row', 'back', true),
('Bent Over Two-Arm Long Bar Row', 'back', true),
('Bent Over Two-Dumbbell Row', 'back', true),
('Bent Over Two-Dumbbell Row With Palms In', 'back', true),
('Bent Press', 'core', true),
('Bicycling', 'quadriceps', true),
('Bicycling, Stationary', 'quadriceps', true),
('Board Press', 'triceps', true),
('Body-Up', 'triceps', true),
('Body Tricep Press', 'triceps', true),
('Bodyweight Flyes', 'chest', true),
('Bodyweight Mid Row', 'back', true),
('Bodyweight Squat', 'quadriceps', true),
('Bodyweight Walking Lunge', 'quadriceps', true),
('Bosu Ball Cable Crunch With Side Bends', 'core', true),
('Bottoms-Up Clean From The Hang Position', 'forearms', true),
('Bottoms Up', 'core', true),
('Box Jump (Multiple Response)', 'hamstrings', true),
('Box Skip', 'hamstrings', true),
('Box Squat', 'quadriceps', true),
('Box Squat with Bands', 'quadriceps', true),
('Box Squat with Chains', 'quadriceps', true),
('Brachialis-SMR', 'biceps', true),
('Bradford/Rocky Presses', 'shoulders', true),
('Butt-Ups', 'core', true),
('Butt Lift (Bridge)', 'glutes', true),
('Butterfly', 'chest', true),
('Cable Chest Press', 'chest', true),
('Cable Crossover', 'chest', true),
('Cable Crunch', 'core', true),
('Cable Deadlifts', 'quadriceps', true),
('Cable Hammer Curls - Rope Attachment', 'biceps', true),
('Cable Hip Adduction', 'quadriceps', true),
('Cable Incline Pushdown', 'back', true),
('Cable Incline Triceps Extension', 'triceps', true),
('Cable Internal Rotation', 'shoulders', true),
('Cable Iron Cross', 'chest', true),
('Cable Judo Flip', 'core', true),
('Cable Lying Triceps Extension', 'triceps', true),
('Cable One Arm Tricep Extension', 'triceps', true),
('Cable Preacher Curl', 'biceps', true),
('Cable Rear Delt Fly', 'shoulders', true),
('Cable Reverse Crunch', 'core', true),
('Cable Rope Overhead Triceps Extension', 'triceps', true),
('Cable Rope Rear-Delt Rows', 'shoulders', true),
('Cable Russian Twists', 'core', true),
('Cable Seated Crunch', 'core', true),
('Cable Seated Lateral Raise', 'shoulders', true),
('Cable Shoulder Press', 'shoulders', true),
('Cable Shrugs', 'back', true),
('Cable Wrist Curl', 'forearms', true),
('Calf-Machine Shoulder Shrug', 'back', true),
('Calf Press', 'calves', true),
('Calf Press On The Leg Press Machine', 'calves', true),
('Calf Raise On A Dumbbell', 'calves', true),
('Calf Raises - With Bands', 'calves', true),
('Calf Stretch Elbows Against Wall', 'calves', true),
('Calf Stretch Hands Against Wall', 'calves', true),
('Calves-SMR', 'calves', true),
('Car Deadlift', 'quadriceps', true),
('Car Drivers', 'shoulders', true),
('Carioca Quick Step', 'glutes', true),
('Cat Stretch', 'back', true),
('Catch and Overhead Throw', 'back', true),
('Chain Handle Extension', 'triceps', true),
('Chain Press', 'chest', true),
('Chair Leg Extended Stretch', 'hamstrings', true),
('Chair Lower Back Stretch', 'back', true),
('Chair Squat', 'quadriceps', true),
('Chair Upper Body Stretch', 'shoulders', true),
('Chest And Front Of Shoulder Stretch', 'chest', true),
('Chest Push from 3 point stance', 'chest', true),
('Chest Push (multiple response)', 'chest', true),
('Chest Push (single response)', 'chest', true),
('Chest Push with Run Release', 'chest', true),
('Chest Stretch on Stability Ball', 'chest', true),
('Child''s Pose', 'back', true),
('Chin-Up', 'back', true),
('Chin To Chest Stretch', 'shoulders', true),
('Circus Bell', 'shoulders', true),
('Clean', 'hamstrings', true),
('Clean Deadlift', 'hamstrings', true),
('Clean Pull', 'quadriceps', true),
('Clean Shrug', 'back', true),
('Clean and Jerk', 'shoulders', true),
('Clean and Press', 'shoulders', true),
('Clean from Blocks', 'quadriceps', true),
('Clock Push-Up', 'chest', true),
('Close-Grip Barbell Bench Press', 'triceps', true),
('Close-Grip Dumbbell Press', 'triceps', true),
('Close-Grip EZ-Bar Curl with Band', 'biceps', true),
('Close-Grip EZ-Bar Press', 'triceps', true),
('Close-Grip EZ Bar Curl', 'biceps', true),
('Close-Grip Front Lat Pulldown', 'back', true),
('Close-Grip Push-Up off of a Dumbbell', 'triceps', true),
('Close-Grip Standing Barbell Curl', 'biceps', true),
('Cocoons', 'core', true),
('Conan''s Wheel', 'quadriceps', true),
('Concentration Curls', 'biceps', true),
('Cross-Body Crunch', 'core', true),
('Cross Body Hammer Curl', 'biceps', true),
('Cross Over - With Bands', 'chest', true),
('Crossover Reverse Lunge', 'back', true),
('Crucifix', 'shoulders', true),
('Crunch - Hands Overhead', 'core', true),
('Crunch - Legs On Exercise Ball', 'core', true),
('Crunches', 'core', true),
('Cuban Press', 'shoulders', true),
('Dancer''s Stretch', 'back', true),
('Dead Bug', 'core', true),
('Deadlift with Bands', 'back', true),
('Deadlift with Chains', 'back', true),
('Decline Barbell Bench Press', 'chest', true),
('Decline Close-Grip Bench To Skull Crusher', 'triceps', true),
('Decline Crunch', 'core', true),
('Decline Dumbbell Bench Press', 'chest', true),
('Decline Dumbbell Flyes', 'chest', true),
('Decline Dumbbell Triceps Extension', 'triceps', true),
('Decline EZ Bar Triceps Extension', 'triceps', true),
('Decline Oblique Crunch', 'core', true),
('Decline Push-Up', 'chest', true),
('Decline Reverse Crunch', 'core', true),
('Decline Smith Press', 'chest', true),
('Deficit Deadlift', 'back', true),
('Depth Jump Leap', 'quadriceps', true),
('Dip Machine', 'triceps', true),
('Dips - Chest Version', 'chest', true),
('Dips - Triceps Version', 'triceps', true),
('Donkey Calf Raises', 'calves', true),
('Double Kettlebell Alternating Hang Clean', 'hamstrings', true),
('Double Kettlebell Jerk', 'shoulders', true),
('Double Kettlebell Push Press', 'shoulders', true),
('Double Kettlebell Snatch', 'shoulders', true),
('Double Kettlebell Windmill', 'core', true),
('Double Leg Butt Kick', 'quadriceps', true),
('Downward Facing Balance', 'glutes', true),
('Drag Curl', 'biceps', true),
('Drop Push', 'chest', true),
('Dumbbell Alternate Bicep Curl', 'biceps', true),
('Dumbbell Bench Press', 'chest', true),
('Dumbbell Bench Press with Neutral Grip', 'chest', true),
('Dumbbell Bicep Curl', 'biceps', true),
('Dumbbell Clean', 'hamstrings', true),
('Dumbbell Floor Press', 'triceps', true),
('Dumbbell Flyes', 'chest', true),
('Dumbbell Incline Row', 'back', true),
('Dumbbell Incline Shoulder Raise', 'shoulders', true),
('Dumbbell Lunges', 'quadriceps', true),
('Dumbbell Lying One-Arm Rear Lateral Raise', 'shoulders', true),
('Dumbbell Lying Pronation', 'forearms', true),
('Dumbbell Lying Rear Lateral Raise', 'shoulders', true),
('Dumbbell Lying Supination', 'forearms', true),
('Dumbbell One-Arm Shoulder Press', 'shoulders', true),
('Dumbbell One-Arm Triceps Extension', 'triceps', true),
('Dumbbell One-Arm Upright Row', 'shoulders', true),
('Dumbbell Prone Incline Curl', 'biceps', true),
('Dumbbell Raise', 'shoulders', true),
('Dumbbell Rear Lunge', 'quadriceps', true),
('Dumbbell Scaption', 'shoulders', true),
('Dumbbell Seated Box Jump', 'quadriceps', true),
('Dumbbell Seated One-Leg Calf Raise', 'calves', true),
('Dumbbell Shoulder Press', 'shoulders', true),
('Dumbbell Shrug', 'back', true),
('Dumbbell Side Bend', 'core', true),
('Dumbbell Squat', 'quadriceps', true),
('Dumbbell Squat To A Bench', 'quadriceps', true),
('Dumbbell Step Ups', 'quadriceps', true),
('Dumbbell Tricep Extension -Pronated Grip', 'triceps', true),
('Dynamic Back Stretch', 'back', true),
('Dynamic Chest Stretch', 'chest', true),
('EZ-Bar Curl', 'biceps', true),
('EZ-Bar Skullcrusher', 'triceps', true),
('Elbow Circles', 'shoulders', true),
('Elbow to Knee', 'core', true),
('Elbows Back', 'chest', true),
('Elevated Back Lunge', 'quadriceps', true),
('Elevated Cable Rows', 'back', true),
('Elliptical Trainer', 'quadriceps', true),
('Exercise Ball Crunch', 'core', true),
('Exercise Ball Pull-In', 'core', true),
('Extended Range One-Arm Kettlebell Floor Press', 'chest', true),
('External Rotation', 'shoulders', true),
('External Rotation with Band', 'shoulders', true),
('External Rotation with Cable', 'shoulders', true),
('Face Pull', 'shoulders', true),
('Farmer''s Walk', 'forearms', true),
('Fast Skipping', 'quadriceps', true),
('Finger Curls', 'forearms', true),
('Flat Bench Cable Flyes', 'chest', true),
('Flat Bench Leg Pull-In', 'core', true),
('Flat Bench Lying Leg Raise', 'core', true),
('Flexor Incline Dumbbell Curls', 'biceps', true),
('Floor Glute-Ham Raise', 'hamstrings', true),
('Floor Press', 'triceps', true),
('Floor Press with Chains', 'triceps', true),
('Flutter Kicks', 'glutes', true),
('Foot-SMR', 'calves', true),
('Forward Drag with Press', 'chest', true),
('Frankenstein Squat', 'quadriceps', true),
('Freehand Jump Squat', 'quadriceps', true),
('Frog Hops', 'quadriceps', true),
('Frog Sit-Ups', 'core', true),
('Front Barbell Squat', 'quadriceps', true),
('Front Barbell Squat To A Bench', 'quadriceps', true),
('Front Box Jump', 'hamstrings', true),
('Front Cable Raise', 'shoulders', true),
('Front Cone Hops (or hurdle hops)', 'quadriceps', true),
('Front Dumbbell Raise', 'shoulders', true),
('Front Incline Dumbbell Raise', 'shoulders', true),
('Front Leg Raises', 'hamstrings', true),
('Front Plate Raise', 'shoulders', true),
('Front Raise And Pullover', 'chest', true),
('Front Squat (Clean Grip)', 'quadriceps', true),
('Front Squats With Two Kettlebells', 'quadriceps', true),
('Front Two-Dumbbell Raise', 'shoulders', true),
('Full Range-Of-Motion Lat Pulldown', 'back', true),
('Gironda Sternum Chins', 'back', true),
('Glute Ham Raise', 'hamstrings', true),
('Glute Kickback', 'glutes', true),
('Goblet Squat', 'quadriceps', true),
('Good Morning', 'hamstrings', true),
('Good Morning off Pins', 'hamstrings', true),
('Gorilla Chin/Crunch', 'core', true),
('Groin and Back Stretch', 'glutes', true),
('Groiners', 'glutes', true),
('Hack Squat', 'quadriceps', true),
('Hammer Curls', 'biceps', true),
('Hammer Grip Incline DB Bench Press', 'chest', true),
('Hamstring-SMR', 'hamstrings', true),
('Hamstring Stretch', 'hamstrings', true),
('Handstand Push-Ups', 'shoulders', true),
('Hang Clean', 'quadriceps', true),
('Hang Clean - Below the Knees', 'quadriceps', true),
('Hang Snatch', 'hamstrings', true),
('Hang Snatch - Below Knees', 'hamstrings', true),
('Hanging Bar Good Morning', 'hamstrings', true),
('Hanging Leg Raise', 'core', true),
('Hanging Pike', 'core', true),
('Heaving Snatch Balance', 'quadriceps', true),
('Heavy Bag Thrust', 'chest', true),
('High Cable Curls', 'biceps', true),
('Hip Circles (prone)', 'glutes', true),
('Hip Extension with Bands', 'glutes', true),
('Hip Flexion with Band', 'quadriceps', true),
('Hip Lift with Band', 'glutes', true),
('Hug A Ball', 'back', true),
('Hug Knees To Chest', 'back', true),
('Hurdle Hops', 'hamstrings', true),
('Hyperextensions (Back Extensions)', 'back', true),
('Hyperextensions With No Hyperextension Bench', 'back', true),
('IT Band and Glute Stretch', 'glutes', true),
('Iliotibial Tract-SMR', 'glutes', true),
('Inchworm', 'hamstrings', true),
('Incline Barbell Triceps Extension', 'triceps', true),
('Incline Bench Pull', 'back', true),
('Incline Cable Chest Press', 'chest', true),
('Incline Cable Flye', 'chest', true),
('Incline Dumbbell Bench With Palms Facing In', 'chest', true),
('Incline Dumbbell Curl', 'biceps', true),
('Incline Dumbbell Flyes', 'chest', true),
('Incline Dumbbell Flyes - With A Twist', 'chest', true),
('Incline Dumbbell Press', 'chest', true),
('Incline Hammer Curls', 'biceps', true),
('Incline Inner Biceps Curl', 'biceps', true),
('Incline Push-Up', 'chest', true),
('Incline Push-Up Close-Grip', 'triceps', true),
('Incline Push-Up Depth Jump', 'chest', true),
('Incline Push-Up Medium', 'chest', true),
('Incline Push-Up Reverse Grip', 'chest', true),
('Incline Push-Up Wide', 'chest', true),
('Intermediate Groin Stretch', 'hamstrings', true),
('Intermediate Hip Flexor and Quad Stretch', 'quadriceps', true),
('Internal Rotation with Band', 'shoulders', true),
('Inverted Row', 'back', true),
('Inverted Row with Straps', 'back', true),
('Iron Cross', 'shoulders', true),
('Iron Crosses (stretch)', 'quadriceps', true),
('Isometric Chest Squeezes', 'chest', true),
('Isometric Neck Exercise - Front And Back', 'shoulders', true),
('Isometric Neck Exercise - Sides', 'shoulders', true),
('Isometric Wipers', 'chest', true),
('JM Press', 'triceps', true),
('Jackknife Sit-Up', 'core', true),
('Janda Sit-Up', 'core', true),
('Jefferson Squats', 'quadriceps', true),
('Jerk Balance', 'shoulders', true),
('Jerk Dip Squat', 'quadriceps', true),
('Jogging, Treadmill', 'quadriceps', true),
('Keg Load', 'back', true),
('Kettlebell Arnold Press', 'shoulders', true),
('Kettlebell Dead Clean', 'hamstrings', true),
('Kettlebell Figure 8', 'core', true),
('Kettlebell Hang Clean', 'hamstrings', true),
('Kettlebell One-Legged Deadlift', 'hamstrings', true),
('Kettlebell Pass Between The Legs', 'core', true),
('Kettlebell Pirate Ships', 'shoulders', true),
('Kettlebell Pistol Squat', 'quadriceps', true),
('Kettlebell Seated Press', 'shoulders', true),
('Kettlebell Seesaw Press', 'shoulders', true),
('Kettlebell Sumo High Pull', 'back', true),
('Kettlebell Thruster', 'shoulders', true),
('Kettlebell Turkish Get-Up (Lunge style)', 'shoulders', true),
('Kettlebell Turkish Get-Up (Squat style)', 'shoulders', true),
('Kettlebell Windmill', 'core', true),
('Kipping Muscle Up', 'back', true),
('Knee Across The Body', 'glutes', true),
('Knee Circles', 'calves', true),
('Knee/Hip Raise On Parallel Bars', 'core', true),
('Knee Tuck Jump', 'hamstrings', true),
('Kneeling Arm Drill', 'shoulders', true),
('Kneeling Cable Crunch With Alternating Oblique Twists', 'core', true),
('Kneeling Cable Triceps Extension', 'triceps', true),
('Kneeling Forearm Stretch', 'forearms', true),
('Kneeling High Pulley Row', 'back', true),
('Kneeling Hip Flexor', 'quadriceps', true),
('Kneeling Jump Squat', 'glutes', true),
('Kneeling Single-Arm High Pulley Row', 'back', true),
('Kneeling Squat', 'glutes', true),
('Landmine 180''s', 'core', true),
('Landmine Linear Jammer', 'shoulders', true),
('Lateral Bound', 'glutes', true),
('Lateral Box Jump', 'glutes', true),
('Lateral Cone Hops', 'glutes', true),
('Lateral Raise - With Bands', 'shoulders', true),
('Latissimus Dorsi-SMR', 'back', true),
('Leg-Over Floor Press', 'chest', true),
('Leg-Up Hamstring Stretch', 'hamstrings', true),
('Leg Extensions', 'quadriceps', true),
('Leg Lift', 'glutes', true),
('Leg Press', 'quadriceps', true),
('Leg Pull-In', 'core', true),
('Leverage Chest Press', 'chest', true),
('Leverage Deadlift', 'quadriceps', true),
('Leverage Decline Chest Press', 'chest', true),
('Leverage High Row', 'back', true),
('Leverage Incline Chest Press', 'chest', true),
('Leverage Iso Row', 'back', true),
('Leverage Shoulder Press', 'shoulders', true),
('Leverage Shrug', 'back', true),
('Linear 3-Part Start Technique', 'hamstrings', true),
('Linear Acceleration Wall Drill', 'hamstrings', true),
('Linear Depth Jump', 'quadriceps', true),
('Log Lift', 'shoulders', true),
('London Bridges', 'back', true),
('Looking At Ceiling', 'quadriceps', true),
('Low Cable Crossover', 'chest', true),
('Low Cable Triceps Extension', 'triceps', true),
('Low Pulley Row To Neck', 'shoulders', true),
('Lower Back-SMR', 'back', true),
('Lower Back Curl', 'core', true),
('Lunge Pass Through', 'hamstrings', true),
('Lunge Sprint', 'quadriceps', true),
('Lying Bent Leg Groin', 'glutes', true),
('Lying Cable Curl', 'biceps', true),
('Lying Cambered Barbell Row', 'back', true),
('Lying Close-Grip Bar Curl On High Pulley', 'biceps', true),
('Lying Close-Grip Barbell Triceps Extension Behind The Head', 'triceps', true),
('Lying Close-Grip Barbell Triceps Press To Chin', 'triceps', true),
('Lying Crossover', 'glutes', true),
('Lying Dumbbell Tricep Extension', 'triceps', true),
('Lying Face Down Plate Neck Resistance', 'shoulders', true),
('Lying Face Up Plate Neck Resistance', 'shoulders', true),
('Lying Glute', 'glutes', true),
('Lying Hamstring', 'hamstrings', true),
('Lying High Bench Barbell Curl', 'biceps', true),
('Lying Leg Curls', 'hamstrings', true),
('Lying Machine Squat', 'quadriceps', true),
('Lying One-Arm Lateral Raise', 'shoulders', true),
('Lying Prone Quadriceps', 'quadriceps', true),
('Lying Rear Delt Raise', 'shoulders', true),
('Lying Supine Dumbbell Curl', 'biceps', true),
('Lying T-Bar Row', 'back', true),
('Lying Triceps Press', 'triceps', true),
('Machine Bench Press', 'chest', true),
('Machine Bicep Curl', 'biceps', true),
('Machine Preacher Curls', 'biceps', true),
('Machine Shoulder (Military) Press', 'shoulders', true),
('Machine Triceps Extension', 'triceps', true),
('Medicine Ball Chest Pass', 'chest', true),
('Medicine Ball Full Twist', 'core', true),
('Medicine Ball Scoop Throw', 'shoulders', true),
('Middle Back Shrug', 'back', true),
('Middle Back Stretch', 'back', true),
('Mixed Grip Chin', 'back', true),
('Monster Walk', 'glutes', true),
('Mountain Climbers', 'quadriceps', true),
('Moving Claw Series', 'hamstrings', true),
('Muscle Snatch', 'hamstrings', true),
('Muscle Up', 'back', true),
('Narrow Stance Hack Squats', 'quadriceps', true),
('Narrow Stance Leg Press', 'quadriceps', true),
('Narrow Stance Squats', 'quadriceps', true),
('Natural Glute Ham Raise', 'hamstrings', true),
('Neck-SMR', 'shoulders', true),
('Neck Press', 'chest', true),
('Oblique Crunches', 'core', true),
('Oblique Crunches - On The Floor', 'core', true),
('Olympic Squat', 'quadriceps', true),
('On-Your-Back Quad Stretch', 'quadriceps', true),
('On Your Side Quad Stretch', 'quadriceps', true),
('One-Arm Dumbbell Row', 'back', true),
('One-Arm Flat Bench Dumbbell Flye', 'chest', true),
('One-Arm High-Pulley Cable Side Bends', 'core', true),
('One-Arm Incline Lateral Raise', 'shoulders', true),
('One-Arm Kettlebell Clean', 'hamstrings', true),
('One-Arm Kettlebell Clean and Jerk', 'shoulders', true),
('One-Arm Kettlebell Floor Press', 'chest', true),
('One-Arm Kettlebell Jerk', 'shoulders', true),
('One-Arm Kettlebell Military Press To The Side', 'shoulders', true),
('One-Arm Kettlebell Para Press', 'shoulders', true),
('One-Arm Kettlebell Push Press', 'shoulders', true),
('One-Arm Kettlebell Row', 'back', true),
('One-Arm Kettlebell Snatch', 'shoulders', true),
('One-Arm Kettlebell Split Jerk', 'shoulders', true),
('One-Arm Kettlebell Split Snatch', 'shoulders', true),
('One-Arm Kettlebell Swings', 'hamstrings', true),
('One-Arm Long Bar Row', 'back', true),
('One-Arm Medicine Ball Slam', 'core', true),
('One-Arm Open Palm Kettlebell Clean', 'hamstrings', true),
('One-Arm Overhead Kettlebell Squats', 'quadriceps', true),
('One-Arm Side Deadlift', 'quadriceps', true),
('One-Arm Side Laterals', 'shoulders', true),
('One-Legged Cable Kickback', 'glutes', true),
('One Arm Against Wall', 'back', true),
('One Arm Chin-Up', 'back', true),
('One Arm Dumbbell Bench Press', 'chest', true),
('One Arm Dumbbell Preacher Curl', 'biceps', true),
('One Arm Floor Press', 'triceps', true),
('One Arm Lat Pulldown', 'back', true),
('One Arm Pronated Dumbbell Triceps Extension', 'triceps', true),
('One Arm Supinated Dumbbell Triceps Extension', 'triceps', true),
('One Half Locust', 'quadriceps', true),
('One Handed Hang', 'back', true),
('One Knee To Chest', 'glutes', true),
('One Leg Barbell Squat', 'quadriceps', true),
('Open Palm Kettlebell Clean', 'hamstrings', true),
('Otis-Up', 'core', true),
('Overhead Cable Curl', 'biceps', true),
('Overhead Lat', 'back', true),
('Overhead Slam', 'back', true),
('Overhead Squat', 'quadriceps', true),
('Overhead Stretch', 'core', true),
('Overhead Triceps', 'triceps', true),
('Pallof Press', 'core', true),
('Pallof Press With Rotation', 'core', true),
('Palms-Down Dumbbell Wrist Curl Over A Bench', 'forearms', true),
('Palms-Down Wrist Curl Over A Bench', 'forearms', true),
('Palms-Up Barbell Wrist Curl Over A Bench', 'forearms', true),
('Palms-Up Dumbbell Wrist Curl Over A Bench', 'forearms', true),
('Parallel Bar Dip', 'triceps', true),
('Pelvic Tilt Into Bridge', 'back', true),
('Peroneals-SMR', 'calves', true),
('Peroneals Stretch', 'calves', true),
('Physioball Hip Bridge', 'glutes', true),
('Pin Presses', 'triceps', true),
('Piriformis-SMR', 'glutes', true),
('Plank', 'core', true),
('Plate Pinch', 'forearms', true),
('Plate Twist', 'core', true),
('Platform Hamstring Slides', 'hamstrings', true),
('Plie Dumbbell Squat', 'quadriceps', true),
('Plyo Kettlebell Pushups', 'chest', true),
('Plyo Push-up', 'chest', true),
('Posterior Tibialis Stretch', 'calves', true),
('Power Clean', 'hamstrings', true),
('Power Clean from Blocks', 'hamstrings', true),
('Power Jerk', 'quadriceps', true),
('Power Partials', 'shoulders', true),
('Power Snatch', 'hamstrings', true),
('Power Snatch from Blocks', 'quadriceps', true),
('Power Stairs', 'hamstrings', true),
('Preacher Curl', 'biceps', true),
('Preacher Hammer Dumbbell Curl', 'biceps', true),
('Press Sit-Up', 'core', true),
('Prone Manual Hamstring', 'hamstrings', true),
('Prowler Sprint', 'hamstrings', true),
('Pull Through', 'glutes', true),
('Pullups', 'back', true),
('Push-Up Wide', 'chest', true),
('Push-Ups - Close Triceps Position', 'triceps', true),
('Push-Ups With Feet Elevated', 'chest', true),
('Push-Ups With Feet On An Exercise Ball', 'chest', true),
('Push Press', 'shoulders', true),
('Push Press - Behind the Neck', 'shoulders', true),
('Push Up to Side Plank', 'chest', true),
('Pushups', 'chest', true),
('Pushups (Close and Wide Hand Positions)', 'chest', true),
('Pyramid', 'back', true),
('Quad Stretch', 'quadriceps', true),
('Quadriceps-SMR', 'quadriceps', true),
('Quick Leap', 'quadriceps', true),
('Rack Delivery', 'shoulders', true),
('Rack Pull with Bands', 'back', true),
('Rack Pulls', 'back', true),
('Rear Leg Raises', 'quadriceps', true),
('Recumbent Bike', 'quadriceps', true),
('Return Push from Stance', 'shoulders', true),
('Reverse Band Bench Press', 'triceps', true),
('Reverse Band Box Squat', 'quadriceps', true),
('Reverse Band Deadlift', 'back', true),
('Reverse Band Power Squat', 'quadriceps', true),
('Reverse Band Sumo Deadlift', 'hamstrings', true),
('Reverse Barbell Curl', 'biceps', true),
('Reverse Barbell Preacher Curls', 'biceps', true),
('Reverse Cable Curl', 'biceps', true),
('Reverse Crunch', 'core', true),
('Reverse Flyes', 'shoulders', true),
('Reverse Flyes With External Rotation', 'shoulders', true),
('Reverse Grip Bent-Over Rows', 'back', true),
('Reverse Grip Triceps Pushdown', 'triceps', true),
('Reverse Hyperextension', 'hamstrings', true),
('Reverse Machine Flyes', 'shoulders', true),
('Reverse Plate Curls', 'biceps', true),
('Reverse Triceps Bench Press', 'triceps', true),
('Rhomboids-SMR', 'back', true),
('Rickshaw Carry', 'forearms', true),
('Rickshaw Deadlift', 'quadriceps', true),
('Ring Dips', 'triceps', true),
('Rocket Jump', 'quadriceps', true),
('Rocking Standing Calf Raise', 'calves', true),
('Rocky Pull-Ups/Pulldowns', 'back', true),
('Romanian Deadlift', 'hamstrings', true),
('Romanian Deadlift from Deficit', 'hamstrings', true),
('Rope Climb', 'back', true),
('Rope Crunch', 'core', true),
('Rope Jumping', 'quadriceps', true),
('Rope Straight-Arm Pulldown', 'back', true),
('Round The World Shoulder Stretch', 'shoulders', true),
('Rowing, Stationary', 'quadriceps', true),
('Runner''s Stretch', 'hamstrings', true),
('Running, Treadmill', 'quadriceps', true),
('Russian Twist', 'core', true),
('Sandbag Load', 'quadriceps', true),
('Scapular Pull-Up', 'back', true),
('Scissor Kick', 'core', true),
('Scissors Jump', 'quadriceps', true),
('Seated Band Hamstring Curl', 'hamstrings', true),
('Seated Barbell Military Press', 'shoulders', true),
('Seated Barbell Twist', 'core', true),
('Seated Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', true),
('Seated Bent-Over Rear Delt Raise', 'shoulders', true),
('Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', true),
('Seated Biceps', 'biceps', true),
('Seated Cable Rows', 'back', true),
('Seated Cable Shoulder Press', 'shoulders', true),
('Seated Calf Raise', 'calves', true),
('Seated Calf Stretch', 'calves', true),
('Seated Close-Grip Concentration Barbell Curl', 'biceps', true),
('Seated Dumbbell Curl', 'biceps', true),
('Seated Dumbbell Inner Biceps Curl', 'biceps', true),
('Seated Dumbbell Palms-Down Wrist Curl', 'forearms', true),
('Seated Dumbbell Palms-Up Wrist Curl', 'forearms', true),
('Seated Dumbbell Press', 'shoulders', true),
('Seated Flat Bench Leg Pull-In', 'core', true),
('Seated Floor Hamstring Stretch', 'hamstrings', true),
('Seated Front Deltoid', 'shoulders', true),
('Seated Glute', 'glutes', true),
('Seated Good Mornings', 'back', true),
('Seated Hamstring', 'hamstrings', true),
('Seated Hamstring and Calf Stretch', 'hamstrings', true),
('Seated Head Harness Neck Resistance', 'shoulders', true),
('Seated Leg Curl', 'hamstrings', true),
('Seated Leg Tucks', 'core', true),
('Seated One-Arm Dumbbell Palms-Down Wrist Curl', 'forearms', true),
('Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'forearms', true),
('Seated One-arm Cable Pulley Rows', 'back', true),
('Seated Overhead Stretch', 'core', true),
('Seated Palm-Up Barbell Wrist Curl', 'forearms', true),
('Seated Palms-Down Barbell Wrist Curl', 'forearms', true),
('Seated Side Lateral Raise', 'shoulders', true),
('Seated Triceps Press', 'triceps', true),
('Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'forearms', true),
('See-Saw Press (Alternating Side Press)', 'shoulders', true),
('Shotgun Row', 'back', true),
('Shoulder Circles', 'shoulders', true),
('Shoulder Press - With Bands', 'shoulders', true),
('Shoulder Raise', 'shoulders', true),
('Shoulder Stretch', 'shoulders', true),
('Side-Lying Floor Stretch', 'back', true),
('Side Bridge', 'core', true),
('Side Hop-Sprint', 'quadriceps', true),
('Side Jackknife', 'core', true),
('Side Lateral Raise', 'shoulders', true),
('Side Laterals to Front Raise', 'shoulders', true),
('Side Leg Raises', 'glutes', true),
('Side Lying Groin Stretch', 'glutes', true),
('Side Neck Stretch', 'shoulders', true),
('Side Standing Long Jump', 'quadriceps', true),
('Side To Side Chins', 'back', true),
('Side Wrist Pull', 'shoulders', true),
('Side to Side Box Shuffle', 'quadriceps', true),
('Single-Arm Cable Crossover', 'chest', true),
('Single-Arm Linear Jammer', 'shoulders', true),
('Single-Arm Push-Up', 'chest', true),
('Single-Cone Sprint Drill', 'quadriceps', true),
('Single-Leg High Box Squat', 'quadriceps', true),
('Single-Leg Hop Progression', 'quadriceps', true),
('Single-Leg Lateral Hop', 'quadriceps', true),
('Single-Leg Leg Extension', 'quadriceps', true),
('Single-Leg Stride Jump', 'quadriceps', true),
('Single Dumbbell Raise', 'shoulders', true),
('Single Leg Butt Kick', 'quadriceps', true),
('Single Leg Glute Bridge', 'glutes', true),
('Single Leg Push-off', 'quadriceps', true),
('Sit-Up', 'core', true),
('Sit Squats', 'quadriceps', true),
('Skating', 'quadriceps', true),
('Sled Drag - Harness', 'quadriceps', true),
('Sled Overhead Backward Walk', 'shoulders', true),
('Sled Overhead Triceps Extension', 'triceps', true),
('Sled Push', 'quadriceps', true),
('Sled Reverse Flye', 'shoulders', true),
('Sled Row', 'back', true),
('Sledgehammer Swings', 'core', true),
('Smith Incline Shoulder Raise', 'shoulders', true),
('Smith Machine Behind the Back Shrug', 'back', true),
('Smith Machine Bench Press', 'chest', true),
('Smith Machine Bent Over Row', 'back', true),
('Smith Machine Calf Raise', 'calves', true),
('Smith Machine Close-Grip Bench Press', 'triceps', true),
('Smith Machine Decline Press', 'chest', true),
('Smith Machine Hang Power Clean', 'hamstrings', true),
('Smith Machine Hip Raise', 'core', true),
('Smith Machine Incline Bench Press', 'chest', true),
('Smith Machine Leg Press', 'quadriceps', true),
('Smith Machine One-Arm Upright Row', 'shoulders', true),
('Smith Machine Overhead Shoulder Press', 'shoulders', true),
('Smith Machine Pistol Squat', 'quadriceps', true),
('Smith Machine Reverse Calf Raises', 'calves', true),
('Smith Machine Squat', 'quadriceps', true),
('Smith Machine Stiff-Legged Deadlift', 'hamstrings', true),
('Smith Machine Upright Row', 'back', true),
('Smith Single-Leg Split Squat', 'quadriceps', true),
('Snatch', 'quadriceps', true),
('Snatch Balance', 'quadriceps', true),
('Snatch Deadlift', 'hamstrings', true),
('Snatch Pull', 'hamstrings', true),
('Snatch Shrug', 'back', true),
('Snatch from Blocks', 'quadriceps', true),
('Speed Band Overhead Triceps', 'triceps', true),
('Speed Box Squat', 'quadriceps', true),
('Speed Squats', 'quadriceps', true),
('Spell Caster', 'core', true),
('Spider Crawl', 'core', true),
('Spider Curl', 'biceps', true),
('Spinal Stretch', 'back', true),
('Split Clean', 'quadriceps', true),
('Split Jerk', 'quadriceps', true),
('Split Jump', 'quadriceps', true),
('Split Snatch', 'hamstrings', true),
('Split Squat with Dumbbells', 'quadriceps', true),
('Split Squats', 'hamstrings', true),
('Squat Jerk', 'quadriceps', true),
('Squat with Bands', 'quadriceps', true),
('Squat with Chains', 'quadriceps', true),
('Squat with Plate Movers', 'quadriceps', true),
('Squats - With Bands', 'quadriceps', true),
('Stairmaster', 'quadriceps', true),
('Standing Alternating Dumbbell Press', 'shoulders', true),
('Standing Barbell Calf Raise', 'calves', true),
('Standing Barbell Press Behind Neck', 'shoulders', true),
('Standing Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', true),
('Standing Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', true),
('Standing Biceps Cable Curl', 'biceps', true),
('Standing Biceps Stretch', 'biceps', true),
('Standing Bradford Press', 'shoulders', true),
('Standing Cable Chest Press', 'chest', true),
('Standing Cable Lift', 'core', true),
('Standing Cable Wood Chop', 'core', true),
('Standing Calf Raises', 'calves', true),
('Standing Concentration Curl', 'biceps', true),
('Standing Dumbbell Calf Raise', 'calves', true),
('Standing Dumbbell Press', 'shoulders', true),
('Standing Dumbbell Reverse Curl', 'biceps', true),
('Standing Dumbbell Straight-Arm Front Delt Raise Above Head', 'shoulders', true),
('Standing Dumbbell Triceps Extension', 'triceps', true),
('Standing Dumbbell Upright Row', 'back', true),
('Standing Elevated Quad Stretch', 'quadriceps', true),
('Standing Front Barbell Raise Over Head', 'shoulders', true),
('Standing Gastrocnemius Calf Stretch', 'calves', true),
('Standing Hamstring and Calf Stretch', 'hamstrings', true),
('Standing Hip Circles', 'glutes', true),
('Standing Hip Flexors', 'quadriceps', true),
('Standing Inner-Biceps Curl', 'biceps', true),
('Standing Lateral Stretch', 'core', true),
('Standing Leg Curl', 'hamstrings', true),
('Standing Long Jump', 'quadriceps', true),
('Standing Low-Pulley Deltoid Raise', 'shoulders', true),
('Standing Low-Pulley One-Arm Triceps Extension', 'triceps', true),
('Standing Military Press', 'shoulders', true),
('Standing Olympic Plate Hand Squeeze', 'forearms', true),
('Standing One-Arm Cable Curl', 'biceps', true),
('Standing One-Arm Dumbbell Curl Over Incline Bench', 'biceps', true),
('Standing One-Arm Dumbbell Triceps Extension', 'triceps', true),
('Standing Overhead Barbell Triceps Extension', 'triceps', true),
('Standing Palm-In One-Arm Dumbbell Press', 'shoulders', true),
('Standing Palms-In Dumbbell Press', 'shoulders', true),
('Standing Palms-Up Barbell Behind The Back Wrist Curl', 'forearms', true),
('Standing Pelvic Tilt', 'back', true),
('Standing Rope Crunch', 'core', true),
('Standing Soleus And Achilles Stretch', 'calves', true),
('Standing Toe Touches', 'hamstrings', true),
('Standing Towel Triceps Extension', 'triceps', true),
('Standing Two-Arm Overhead Throw', 'shoulders', true),
('Star Jump', 'quadriceps', true),
('Step-up with Knee Raise', 'glutes', true),
('Step Mill', 'quadriceps', true),
('Stiff-Legged Barbell Deadlift', 'hamstrings', true),
('Stiff-Legged Dumbbell Deadlift', 'hamstrings', true),
('Stiff Leg Barbell Good Morning', 'back', true),
('Stomach Vacuum', 'core', true),
('Straight-Arm Dumbbell Pullover', 'chest', true),
('Straight-Arm Pulldown', 'back', true),
('Straight Bar Bench Mid Rows', 'back', true),
('Straight Raises on Incline Bench', 'shoulders', true),
('Stride Jump Crossover', 'quadriceps', true),
('Sumo Deadlift', 'hamstrings', true),
('Sumo Deadlift with Bands', 'hamstrings', true),
('Sumo Deadlift with Chains', 'hamstrings', true),
('Superman', 'back', true),
('Supine Chest Throw', 'triceps', true),
('Supine One-Arm Overhead Throw', 'core', true),
('Supine Two-Arm Overhead Throw', 'core', true),
('Suspended Fallout', 'core', true),
('Suspended Push-Up', 'chest', true),
('Suspended Reverse Crunch', 'core', true),
('Suspended Row', 'back', true),
('Suspended Split Squat', 'quadriceps', true),
('Svend Press', 'chest', true),
('T-Bar Row with Handle', 'back', true),
('Tate Press', 'triceps', true),
('The Straddle', 'hamstrings', true),
('Thigh Abductor', 'glutes', true),
('Thigh Adductor', 'glutes', true),
('Tire Flip', 'quadriceps', true),
('Toe Touchers', 'core', true),
('Torso Rotation', 'core', true),
('Trail Running/Walking', 'quadriceps', true),
('Trap Bar Deadlift', 'quadriceps', true),
('Tricep Dumbbell Kickback', 'triceps', true),
('Tricep Side Stretch', 'triceps', true),
('Triceps Overhead Extension with Rope', 'triceps', true),
('Triceps Pushdown', 'triceps', true),
('Triceps Pushdown - Rope Attachment', 'triceps', true),
('Triceps Pushdown - V-Bar Attachment', 'triceps', true),
('Triceps Stretch', 'triceps', true),
('Tuck Crunch', 'core', true),
('Two-Arm Dumbbell Preacher Curl', 'biceps', true),
('Two-Arm Kettlebell Clean', 'shoulders', true),
('Two-Arm Kettlebell Jerk', 'shoulders', true),
('Two-Arm Kettlebell Military Press', 'shoulders', true),
('Two-Arm Kettlebell Row', 'back', true),
('Underhand Cable Pulldowns', 'back', true),
('Upper Back-Leg Grab', 'hamstrings', true),
('Upper Back Stretch', 'back', true),
('Upright Barbell Row', 'shoulders', true),
('Upright Cable Row', 'back', true),
('Upright Row - With Bands', 'back', true),
('Upward Stretch', 'shoulders', true),
('V-Bar Pulldown', 'back', true),
('V-Bar Pullup', 'back', true),
('Vertical Swing', 'hamstrings', true),
('Walking, Treadmill', 'quadriceps', true),
('Weighted Ball Hyperextension', 'back', true),
('Weighted Ball Side Bend', 'core', true),
('Weighted Bench Dip', 'triceps', true),
('Weighted Crunches', 'core', true),
('Weighted Jump Squat', 'quadriceps', true),
('Weighted Pull Ups', 'back', true),
('Weighted Sissy Squat', 'quadriceps', true),
('Weighted Sit-Ups - With Bands', 'core', true),
('Weighted Squat', 'quadriceps', true),
('Wide-Grip Barbell Bench Press', 'chest', true),
('Wide-Grip Decline Barbell Bench Press', 'chest', true),
('Wide-Grip Decline Barbell Pullover', 'chest', true),
('Wide-Grip Lat Pulldown', 'back', true),
('Wide-Grip Pulldown Behind The Neck', 'back', true),
('Wide-Grip Rear Pull-Up', 'back', true),
('Wide-Grip Standing Barbell Curl', 'biceps', true),
('Wide Stance Barbell Squat', 'quadriceps', true),
('Wide Stance Stiff Legs', 'hamstrings', true),
('Wind Sprints', 'core', true),
('Windmills', 'glutes', true),
('World''s Greatest Stretch', 'hamstrings', true),
('Wrist Circles', 'forearms', true),
('Wrist Roller', 'forearms', true),
('Wrist Rotations with Straight Bar', 'forearms', true),
('Yoke Walk', 'quadriceps', true),
('Zercher Squats', 'quadriceps', true),
('Zottman Curl', 'biceps', true),
('Zottman Preacher Curl', 'biceps', true);


-- Insert into actual table, skipping duplicates based on name + is_system
INSERT INTO public.exercises (name, target_muscle_group, is_system, created_at, updated_at)
SELECT 
    t.name, 
    t.target_muscle_group, 
    t.is_system,
    NOW(),
    NOW()
FROM temp_exercises t
WHERE NOT EXISTS (
    SELECT 1 FROM public.exercises e 
    WHERE LOWER(e.name) = LOWER(t.name) 
    AND e.is_system = true 
    AND e.deleted_at IS NULL
);

DROP TABLE temp_exercises;
